run("SetModel")
run("SetParameters")
run("Weather2Arrays") % run("AbsHumCalculator") 
run("SetInputs")
run("SetStates")
run("SetDynParameters")
run("AirProperties")
run("CHTC_Greenhouse")
run("Structuur")